sonar.projectKey=fentz26_EnvCP
sonar.language=ts
sonar.sources=src
sonar.tests=__tests__
sonar.test.inclusions=**/*.test.ts
sonar.source.exclusions=**/node_modules/**,**/dist/**
sonar.coverage.exclusions=**/cli/index.ts,**/index.ts,**/utils/keychain.ts
sonar.javascript.node.maxspace=4096
sonar.scm.revision=${{ github.sha }}
